
title: My Resume
url: 'http://juliandomingo.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Julian Domingo
tagline: Junior Software Engineering Student

#sidebar links
phone: 713-628-6856
website: juliandomingo.github.io #do not add http://
github: juliandomingo

#Update all the sections by editing the files inside _includes folder.
